In [53]:
#Question 1 and Question 2 
import pandas as pd

# Question 1
excel_file = "timetable.xlsx"


all_sheets = pd.read_excel(excel_file, header=None, skiprows=4, sheet_name=None)

# Initialize an empty list
data_frames = []

# Loop through the sheets 
for sheet_name, df in all_sheets.items():
    # Drop columns with no data
    df = df.dropna(axis=1, how='all')
    
    # Append the processed DataFrame to the list
    data_frames.append(df)


df = pd.concat(data_frames, ignore_index=True)

# Get the location of elements in the DataFrame
location_of_element = df.loc[2]


df

,0,1,4,7,10,11,13,14,16,19,22,8
0,Room,08:30-09:50,10:00-11:20,11:30-12:50,01:00-02:20,NaN,02:30-03:50,NaN,03:55-05:15,05:20-06:40,06:45-08:05,NaN
1,C-301,Func Eng (CS-A) 08:30-10:15,NaN,PF (CS-A),AP (CS-A),NaN,Calculus (CS-A),NaN,NaN,Adv OS,Adv Algo,NaN
2,C-302,AP (CS-B),PF (CS-B),Calculus (CS-B),NaN,Func Eng (CS-B) 02:00-03:45,NaN,NaN,Info Sec (CS-F) ReSch,Adv Comp Net,NaN,NaN
3,C-303,PF (CS-C),Calculus (CS-C),Islamic (CS-C) 11:30-01:15,NaN,Islamic (CS-D) 02:00-03:45,NaN,NaN,Calculus (CS-D) ReSch,Adv Qual Assur,Adv S/w Arch,NaN
4,C-304,Calculus (CS-D),PF (CS-D),AP (CS-D),Automata (CS-E),NaN,AP (CS-C),NaN,NaN,Deep Learning,Adv AI,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
169,A-Mehran 2,Data St Lab (DS-D),NaN,Deep Learning (B),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,A-CALL-1,Func Eng Lab (CS-D1),NaN,Func Eng Lab (CS-A1),NaN,NaN,Func Eng Lab (CS-C1),NaN,NaN,NaN,NaN,NaN
171,A-CALL-2,Func Eng Lab (CS-D2),NaN,Func Eng Lab (CS-A2),NaN,NaN,Func Eng Lab (CS-C2),NaN,NaN,NaN,NaN,NaN
172,A-CALL-3,NaN,NaN,NaN,FSM,NaN,FSM,NaN,NaN,NaN,NaN,NaN
173,B-Digital,DLD Lab (AI-D),NaN,DLD Lab (AI-C),NaN,NaN,DLD Lab (CY-A),NaN,NaN,NaN,NaN,NaN

In [47]:
#Question 3 
import pandas as pd

subject = input("Enter the subject: ")
excel_file = 'timetable.xlsx'  

class_names = []
room_numbers = []
class_times = []
days_name = []

# Read data from all sheets in the Excel file
all_data = pd.read_excel(excel_file, sheet_name=None, header=None, skiprows=4)

for sheet_name, df in all_data.items():
    # Drop columns with all values as NaN
    df.dropna(axis=1, how='all', inplace=True)
    
    for index, row in df.iterrows():
        row_values = [str(cell) for cell in row]
        for col_index in range(1, len(row_values)):
            if subject in row_values[col_index]:
                class_name = row_values[col_index]
                room_number = row_values[0]

                class_times_dict = {
                    1: "08:30-09:50",
                    2: "10:00-11:20",
                    3: "11:30-12:50",
                    4: "1:00-2:20",
                    5: "2:30-3:50",
                    6: "3:55-5:15",
                    7: "5:20-7:20",
                    8: "1:00-2:20",
                    9: "8:30-9:50",
                    10: "8:30-9:50"
                }

                class_time_ = class_times_dict.get(col_index, "Unknown")
                class_names.append(class_name)
                room_numbers.append(room_number)
                class_times.append(class_time_)
                days_name.append(sheet_name)

if class_names:
    for i in range(len(class_names)):
        print(f"Class {i + 1} - Class info: {class_names[i]}, Room: {room_numbers[i]}, Class Times: {class_times[i]}, Day: {days_name[i]}")
else:
    print(f"No classes found for {subject}.")

Class 1 - Class info: Prog for AI (AI-B), Room: C-408, Class Times: 2:30-3:50, Day: Tuesday
Class 2 - Class info: Prog for AI (AI-A), Room: A-311, Class Times: 10:00-11:20, Day: Tuesday
Class 3 - Class info: Prog for AI (AI-C), Room: C-407, Class Times: 1:00-2:20, Day: Wednesday
Class 4 - Class info: Prog for AI (AI-D), Room: C-408, Class Times: 11:30-12:50, Day: Wednesday
Class 5 - Class info: Prog for AI (AI-A), Room: A-311, Class Times: 10:00-11:20, Day: Thursday
Class 6 - Class info: Prog for AI (AI-B), Room: A-311, Class Times: 1:00-2:20, Day: Thursday
Class 7 - Class info: Prog for AI Lab (AI-D), Room: C-GPU Lab, Class Times: 11:30-12:50, Day: Thursday

In [ ]:
#Question 4
import pandas as pd
import openpyxl
# Specify the Excel file
excel_file = "timetable.xlsx"

# Read all sheets into a dictionary
all_sheets = pd.read_excel(excel_file, header=None, skiprows=4, sheet_name=None)

# Loop through the sheets and process them as needed
for sheet_name, df in all_sheets.items():
    
    df = df.dropna(axis=1, how='all')
    #Testing bugs
    # Extract the row with the element location 
    #location_of_element = df.loc[2]

    # Print the sheet name
    #print(f"Sheet Name: {sheet_name}")

    # Print the row with the element location
    #print(location_of_element)

    # Print the DataFrame
    #print(df)


file_path = 'timetable.xlsx'  
workbook = openpyxl.load_workbook(file_path)

# Create a new workbook to store the results
new_workbook = openpyxl.Workbook()

# Get user input
search_value = input(f"Enter the value to search for in the '{sheet_name}' sheet: ")


# Iterate through all sheets in the input workbook
for sheet_name in workbook.sheetnames:
    # Select the current sheet
    sheet = workbook[sheet_name]


    # Flag to keep track if the value is found
    value_found = False

    # Initialize rgb_color variable
    rgb_color = None

    # for finding the rgb color value of any cell
    for row in sheet.iter_rows(min_row=1, max_row=40, min_col=1, max_col=sheet.max_column):
        for cell in row:
            if cell.value == search_value:
                # Get the RGB value of the cell's fill color
                if cell.fill.start_color is not None:
                    rgb_color = cell.fill.start_color.rgb
                    value_found = True
                    break

    # If the value is not found
    if not value_found:
        print(f'The value "{search_value}" was not found in the first four rows of the "{sheet_name}" sheet.')
    else:
        # Create a new sheet in the new workbook with the same name as the current sheet
        new_sheet = new_workbook.create_sheet(title=sheet_name)

        # for finding those cells which have the same rgb color value
        if rgb_color:
            for row in sheet.iter_rows(min_row=4, max_row=sheet.max_row, min_col=1, max_col=sheet.max_column):
                for cell in row:
                    if cell.fill.start_color.rgb == rgb_color:
                        cell_coordinate = cell.coordinate
                        cell_value = cell.value  # Get the cell's value

                        # Set the value in the new sheet using the cell coordinate
                        new_sheet[cell_coordinate] = cell_value

        # Copy values from specific ranges 
        for row_index in range(1, 42):
            original_value = sheet.cell(row=row_index, column=1).value
            new_sheet.cell(row=row_index, column=1, value=original_value)

        for col_index in range(1, 24):
            original_value = sheet.cell(row=5, column=col_index).value
            new_sheet.cell(row=5, column=col_index, value=original_value)

# Remove the default sheet created by openpyxl in the new workbook
new_workbook.remove(new_workbook['Sheet'])

# Save the new workbook
new_workbook.save('result.xlsx')

In [1]:
#Question 5 
import pandas as pd

# Define a mapping of full course names to their abbreviations
course_abbreviations = {
    "Programming Fundamentals (CS)": "PF (CS)",
    "Programming Fundamentals (AI)": "PF (AI)",
    "Programming Fundamentals (DS)": "PF (DS)",
    "Data Structures (CS)": "Data St (CS)",
    "Discrete Structures (CS)":"Discrete (CS)",
    "Computer Organization & Assembly Language (CS)":"COAL (CS)",
    "Data Structures (AI)":"Data St (AI)",
    "Programming for AI (AI)":"Prog for AI (AI)",
    "Digital Logic Design (AI)":"DLD (AI)",
    "Data Structures (DS)":"Data St (DS)",
    "Introduction to Data Science (DS)":"Intro to DS (DS)",
    "Fundamentals of Software Engineering (DS)":"Fund of SE (DS)",
    "Fundamentals of Software Engineering (CY)":"Fund of SE (CY)",
    "Data Structures (CY)":"Data St (CY)",
    "Digital Logic Design (CY)":"DLD(CY)",
    "Networks & Cyber Security-1 (CY)":"Net & Cy Sec-I (CY)",
    "Data Structures (SE)":"Data St (SE)",
    "Human Computer Interaction (SE)":"HCI (SE)", 
    "Software Requirements Engineering (SE)":"S/w Re-Engg (SE)",
    "Computer Networks (CS)": "Comp Net (CS)",
    "Software Design & Analysis (CS)": "SDA (CS)", 
    "Theory of Automata (CS)": "Automata (CS)",
    "Statistical Modeling (MT-Elective)": "Stat & Modeling (CS)", 
    "Artificial Intelligence ":"AI (CS)", 
    "Robotics Technology (BS-Robotics)": "Robo Tech (CS-Robo)",
    "Knowledge Representation & Reasoning (AI)": "Knowl Rep (AI)", 
    "Machine Learning (AI)": "ML (AI)",
    "Operating Systems (AI)":"OS (AI)", 
    "Design & Analysis of Algorithms (AI)": "Algo (AI)",
    "Operating Systems (DS)":"OS (DS)", 
    "Design & Analysis of Algorithms (DS)": "Algo(DS)", 
    "Data Analysis & Visualization (DS)": "DAV (DS)", 
    "Data Warehousing & Business Intelligence (DS)": "DataWare (DS)",
    "Operating Systems (CY)": "OS(CY)", 
    "Network and Cyber Security-II (CY)":"Net & Cy Sec-I (CY)", 
    "Database Systems (CY)": "DB(CY)",
    "Design & Analysis of Algorithms (CY)":"Algo (CY)",
    "Operating Systems (SE)":"OS (SE)", 
    "Web Engineering (SE)":"Web Engg (SE)", 
    "Software Quality Engineering (SE)":"S/w Qual Engg (SE)",
    "Design & Analysis of Algorithms (SE)":"Algo (SE)", 
    "Information Security (CS)":"Info Sec (CS)", 
    "Professional Practices (CS)":"PPIT (CS)", 

    # Add more mappings as needed
}
#Creating exception for repeat courses
repeat_courses_22 = {"Object Oriented Programming (CS)":"OOP (CS)",
"Object Oriented Programming (AI&DS)":"OOP (AI/DS)",
"Object Oriented Programming (CY)":"OOP (CY)",
"Object Oriented Programming (SE)":"OOP (SE)",

}
repeat_courses_21 = {"Database Systems (CS)":"DBS(CS)", 
"Database Systems (AI&DS)":"DBS(AI/DS)", 
"Database Systems (SE))": "DBS(SE)",
"Operating Systems (CS)":"OS(CS)", }
master_courses = {"Data Science Tools and Techniques (DS)": "DS Tools & Tech"}
course_allocator_df = pd.read_excel('course_instructors.xlsx', skiprows=2)

course_allocator_df['Course'].fillna(method='ffill', inplace=True)
course_allocator_df['Section'].fillna(method='ffill', inplace=True)

# Create a dictionary to map teachers to their assigned classes
teacher_to_classes = {}
current_teacher = None
previous_course_name = None
flag_1 = False
flag_2 = False
flag_master = False
for index, row in course_allocator_df.iterrows():
    course_name = row['Course']
    section = row['Section']
    teacher_name = row['Course Instructor']

    if not pd.isna(course_name) and course_name.strip().lower() != 'naan':
        current_teacher = teacher_name
        previous_course_name = course_name

    # Replace course name with abbreviation if it exists in the mapping

    if course_name not in repeat_courses_22 and course_name not in repeat_courses_21:
        course_name_abbreviation = course_abbreviations.get(course_name, course_name)
    elif course_name in repeat_courses_22:
        flag_1 = True
        course_name_abbreviation = repeat_courses_22.get(course_name, course_name)
    elif course_name in repeat_courses_21:
        flag_2 = True
        course_name_abbreviation = repeat_courses_21.get(course_name, course_name)
    if course_name in master_courses:
        flag_master = True
        course_name_abbreviation = master_courses.get(course_name, course_name)
    # Format the section in the desired way
    section_str_form = str(section)
    course_name_modi = str(course_name_abbreviation)
    #Formatting all strings according to timetable and course allocator map to get maximum accuracy
    if(flag_1==False):
        course_name_abbreviation = course_name_modi[:-1]
        section_formatted = f"{str(course_name_abbreviation)}-{str(section_str_form[-1])})"
    if(flag_1 ):
        course_name_abbreviation = course_name_modi[:-1]
        section_formatted = f"{str(course_name_abbreviation)}-{str(section_str_form[-1])}, 22)"
    if(flag_2):
        section_formatted = f"{str(course_name_abbreviation)}-{str(section_str_form[-1])}, 21)"
    if(flag_master):
        section_formatted = f"{course_name_abbreviation}"
        # Add the course to the current teacher
    if current_teacher:
        if current_teacher not in teacher_to_classes:
            teacher_to_classes[current_teacher] = [(course_name, section_formatted)]
        else:
            teacher_to_classes[current_teacher].append((course_name, section_formatted))

# Function to get classes assigned to a teacher
def get_classes_for_teacher(teacher_name):
    if teacher_name in teacher_to_classes:
        return teacher_to_classes[teacher_name]
    else:
        return []

# Example: Get classes assigned to a specific teacher (User Input)
user_input_teacher = input("Enter the name of the teacher: ")
assigned_classes = get_classes_for_teacher(user_input_teacher)
if assigned_classes:
    print(f"Classes assigned to {user_input_teacher}:")
    for course, section in assigned_classes:
        print(f"Course: {course}, Section: {section}")
else:
    print(f"{user_input_teacher} is not assigned to any classes.")
new_list_for_time_table = []
for i in range(len(assigned_classes)):
    course, section = assigned_classes[i]
    new_list_for_time_table.append(section)
  
excel_file = 'timetable.xlsx'  # Replace with the actual file path

for subject in new_list_for_time_table:
    class_names = []
    room_numbers = []
    class_times = []
    days_name = []

    # Read data from all sheets in the Excel file
    all_data = pd.read_excel(excel_file, sheet_name=None, header=None, skiprows=4)

    for sheet_name, df in all_data.items():
        # Drop columns with all values as NaN
        df.dropna(axis=1, how='all', inplace=True)

        for index, row in df.iterrows():
            row_values = [str(cell) for cell in row]
            for col_index in range(1, len(row_values)):
                if subject in row_values[col_index]:
                    class_name = row_values[col_index]
                    room_number = row_values[0]

                    class_times_dict = {
                        1: "08:30-09:50",
                        2: "10:00-11:20",
                        3: "11:30-12:50",
                        4: "1:00-2:20",
                        5: "2:30-3:50",
                        6: "3:55-5:15",
                        7: "5:20-7:20",
                        8: "1:00-2:20",
                        9: "8:30-9:50",
                        10: "8:30-9:50"
                    }

                    class_time_ = class_times_dict.get(col_index, "Unknown")
                    class_names.append(class_name)
                    room_numbers.append(room_number)
                    class_times.append(class_time_)
                    days_name.append(sheet_name)

    if class_names:
        for i in range(len(class_names)):
            print(f"Class {i + 1} - Class info: {class_names[i]}, Room: {room_numbers[i]}, Class Times: {class_times[i]}, Day: {days_name[i]}")
    else:
        print(f"No classes found for {subject}.")

Classes assigned to Ms. Khadija Mahmood:
Course: Introduction to Data Science (DS), Section: Intro to DS (DS-B)
Course: Introduction to Data Science (DS), Section: Intro to DS (DS-D)
Class 1 - Class info: Intro to DS (DS-B), Room: B-130, Class Times: 08:30-09:50, Day: Tuesday
Class 2 - Class info: Intro to DS (DS-B), Room: C-408, Class Times: 08:30-09:50, Day: Thursday
Class 1 - Class info: Intro to DS (DS-D), Room: C-407, Class Times: 2:30-3:50, Day: Tuesday
Class 2 - Class info: Intro to DS (DS-D), Room: C-410, Class Times: 08:30-09:50, Day: Wednesday