In [4]:
import pandas as pd
timetable_df = pd.read_excel('timetable.xlsx', header=None, skiprows=4)

excel_file = "timetable.xlsx"  
import pandas as pd

xl = pd.ExcelFile(excel_file)

# Initialize an empty DataFrame to store the merged data
merged_df = pd.DataFrame()


for sheet_name in xl.sheet_names:
    # Read each sheet into a DataFrame
    df = xl.parse(sheet_name)
    
    # Append the DataFrame to the merged DataFrame
    merged_df = merged_df.append(df, ignore_index=True)


merged_df.to_excel('merged_timetable.xlsx', index=False)
print(merged_df)

C:\Users\Shahz\AppData\Local\Temp\ipykernel_16136\1295770155.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_df = merged_df.append(df, ignore_index=True)
C:\Users\Shahz\AppData\Local\Temp\ipykernel_16136\1295770155.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_df = merged_df.append(df, ignore_index=True)
C:\Users\Shahz\AppData\Local\Temp\ipykernel_16136\1295770155.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_df = merged_df.append(df, ignore_index=True)
C:\Users\Shahz\AppData\Local\Temp\ipykernel_16136\1295770155.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_df = merged_df.append(df, ignore_index=True)

    Monday FSC\nTimeTable for Fall-2023  Unnamed: 2  Unnamed: 3  BS CS (2023)  \
0      NaN                          NaN         NaN         NaN  BS CS (2022)
1      NaN                          NaN         NaN         NaN  BS CS (2021)
2      NaN                          NaN         NaN         NaN  BS CS (2020)
3     Room                  08:30-09:50         NaN         NaN   10:00-11:20
4    C-301  Func Eng (CS-A) 08:30-10:15         NaN         NaN           NaN
..     ...                          ...         ...         ...           ...
181    NaN           Data St Lab (DS-D)         NaN         NaN           NaN
182    NaN         Func Eng Lab (CS-D1)         NaN         NaN           NaN
183    NaN         Func Eng Lab (CS-D2)         NaN         NaN           NaN
184    NaN                          NaN         NaN         NaN           NaN
185    NaN               DLD Lab (AI-D)         NaN         NaN           NaN

     Unnamed: 5  Unnamed: 6          BS DS (2023) Unnamed: 8  Unnamed: 9  ...  \
0           NaN         NaN          BS DS (2022)        NaN         NaN  ...
1           NaN         NaN          BS DS (2021)        NaN         NaN  ...
2           NaN         NaN          BS DS (2020)        NaN         NaN  ...
3           NaN         NaN           11:30-12:50        NaN         NaN  ...
4           NaN         NaN             PF (CS-A)        NaN         NaN  ...
..          ...         ...                   ...        ...         ...  ...
181         NaN         NaN     Deep Learning (B)        NaN         NaN  ...
182         NaN         NaN  Func Eng Lab (CS-A1)        NaN         NaN  ...
183         NaN         NaN  Func Eng Lab (CS-A2)        NaN         NaN  ...
184         NaN         NaN                   NaN        NaN         NaN  ...
185         NaN         NaN        DLD Lab (AI-C)        NaN         NaN  ...

    Unnamed: 17 Unnamed: 18  BS Electives (19 Batch, CS/AI/SE) Unnamed: 20  \
0           NaN         NaN                     Repeat Courses         NaN
1           NaN         NaN          MS Electives (All Prgrms)         NaN
2           NaN         NaN                            MS (AI)         NaN
3           NaN         NaN                       05:20-06:40          NaN
4           NaN         NaN                             Adv OS         NaN
..          ...         ...                                ...         ...
181         NaN         NaN                                NaN         NaN
182         NaN         NaN                                NaN         NaN
183         NaN         NaN                                NaN         NaN
184         NaN         NaN                                NaN         NaN
185         NaN         NaN                                NaN         NaN

    Unnamed: 21      MS (CS) Tuesday  BS Electives (19 Batch, CS/AI/DS/CY)  \
0           NaN      MS (DS)     NaN                                   NaN
1           NaN      MS (SE)     NaN                                   NaN
2           NaN     MS (CNS)     NaN                                   NaN
3           NaN  06:45-08:05     NaN                                   NaN
4           NaN     Adv Algo     NaN                                   NaN
..          ...          ...     ...                                   ...
181         NaN          NaN     NaN                                   NaN
182         NaN          NaN     NaN                                   NaN
183         NaN          NaN     NaN                                   NaN
184         NaN          NaN     NaN                                   NaN
185         NaN          NaN     NaN                                   NaN

     Wednesday    Thursday
0          NaN         NaN
1          NaN         NaN
2          NaN         NaN
3          NaN         NaN
4          NaN         NaN
..         ...         ...
181        NaN  A-Mehran 2
182        NaN    A-CALL-1
183        NaN    A-CALL-2
184        NaN    A-CALL-3
185        NaN   B-Digital

[186 rows x 27 columns]

Sheet 'Monday' not found in the merged Excel file.
Sheet 'Tuesday' not found in the merged Excel file.
Sheet 'Wednesday' not found in the merged Excel file.
Sheet 'Thursday' not found in the merged Excel file.

In [11]:
df = pd.read_excel(excel_file, header=None, skiprows=4)
df = df.dropna(axis=1, how='all')
location_of_element = df.loc[2]
print(location_of_element)
print(df)

0                           C-302
1                       AP (CS-B)
4                       PF (CS-B)
7                 Calculus (CS-B)
10                            NaN
11    Func Eng (CS-B) 02:00-03:45
13                            NaN
14                            NaN
16          Info Sec (CS-F) ReSch
19                   Adv Comp Net
22                            NaN
Name: 2, dtype: object
           0                                   1                       4   \
0        Room                         08:30-09:50             10:00-11:20
1       C-301         Func Eng (CS-A) 08:30-10:15                     NaN
2       C-302                           AP (CS-B)               PF (CS-B)
3       C-303                           PF (CS-C)         Calculus (CS-C)
4       C-304                     Calculus (CS-D)               PF (CS-D)
5       C-305               Reserved for HoD (CS)            TBW (CS-F/H)
6       C-307                     Calculus (AI-B)               AP (AI-B)
7       C-308                           AP (CY-B)               PF (CY-B)
8       C-309                           AP (AI-A)               PF (AI-A)
9       C-310         Func Eng (CS-G) 08:30-10:15                     NaN
10      C-311                     Discrete (CS-B)         Discrete (CS-A)
11      C-401                           PF (CY-A)         Calculus (CY-A)
12      C-402                         COAL (CS-D)               LA (CS-D)
13      C-403                      Data St (CS-E)             COAL (CS-E)
14      C-404  Ideology of Pak (DS-C) 08:30-10:15                     NaN
15      C-405                      Data St (SE-A)          Data St (CS-F)
16      C-406                           LA (SE-F)               LA (SE-G)
17      C-407                                  SE          Data St (SE-B)
18      C-408                          HCI (SE-C)     S/w Req Engg (SE-C)
19      C-409                 S/w Req Engg (SE-D)              HCI (SE-D)
20      C-410                     Comp Net (CS-E)              SDA (CS-E)
21      B-130                          SDA (CS-C)    Data St (SE-F) ReSch
22      B-227                     Automata (CS-A)         Automata (CS-Y)
23      B-229                          TBW (CS-G)  Stat & Modeling (CS-B)
24      B-230              Stat & Modeling (CS-H)               AI (CS-A)
25      A-108                         Algo (DS-M)             Algo (DS-N)
26      A-211                         Algo (AI-J)               ML (AI-J)
27      A-301                           OS (AI-K)        Knowl Rep (AI-K)
28      A-302                         Algo (CY-T)          Data St (CS-G)
29      A-303                          TBW (DS-N)              TBW (DS-M)
30      A-305                         COAL (CS-C)               LA (CS-C)
31      A-310                     Ethical Hacking       OOP (AI/DS-A, 22)
32      A-311                   OOP (AI/DS-C, 22)       Deep Learning (A)
33      A-314                Data St (SE-G) ReSch       Cloud Comp (SE-B)
34      A-315                Islamic (CS-F) ReSch                     FSM
35      A-316                                 NaN                     FSM
36      C-110                             SMD (A)       Comp Net (CS-C/D)
37  Seminar A                                 NaN                     NaN

                            7                            10  \
0                  11:30-12:50                  01:00-02:20
1                    PF (CS-A)                    AP (CS-A)
2              Calculus (CS-B)                          NaN
3   Islamic (CS-C) 11:30-01:15                          NaN
4                    AP (CS-D)              Automata (CS-E)
5                          NaN                          NaN
6                    PF (AI-B)              Calculus (AI-A)
7              Calculus (CY-B)                    AP (CY-A)
8     Stat & Modeling (CS-F/G)   Islamic (CS-E) 01:15-03:00
9               Data St (CS-H)               Data St (CS-C)
10                 COAL (CS-A)                  COAL (CS-B)
11                   LA (CS-J)                    LA (CS-K)
12              Data St (CS-D)            Cloud Comp (SE-A)
13             Discrete (CS-E)                    LA (SE-E)
14           Fund of SE (CY-C)    S/w Req Engg (SE-C) ReSch
15                  DLD (CY-D)            Fund of SE (CY-D)
16                  HCI (SE-A)          S/w Req Engg (SE-A)
17         S/w Req Engg (SE-B)                   HCI (SE-B)
18              Data St (SE-C)               Data St (SE-D)
19                TBW (CS-B/Z)              Automata (CS-D)
20             Automata (CS-C)                   SDA (CS-A)
21           Comp Net (CS-A/Y)                          NaN
22                  SDA (CS-D)                   SDA (CS-Y)
23         Robo Tech (CS-Robo)       Stat & Modeling (CS-Z)
24     Fund of SE (CY-A) ReSch                          NaN
25               MLOPs (AI-JK)  Blockchain & Crypto (AI-JK)
26            Knowl Rep (AI-J)                          NaN
27                 Algo (AI-K)                    ML (AI-K)
28                 Algo (SE-P)                    OS (SE-P)
29                   OS (SE-Q)                  Algo (SE-Q)
30                   LA (CS-B)                          NaN
31           OOP (AI/DS-B, 22)                          NaN
32                         DIP                          NaN
33                   AI (CS-B)                          NaN
34        Islamic (CS-E) ReSch                          NaN
35                         FSM                          FSM
36                     SMD (B)                     Reserved
37                         NaN                          NaN

                             11                                 13  \
0                           NaN                        02:30-03:50
1                           NaN                    Calculus (CS-A)
2   Func Eng (CS-B) 02:00-03:45                                NaN
3    Islamic (CS-D) 02:00-03:45                                NaN
4                           NaN                          AP (CS-C)
5                           NaN  Func Eng (AI-A) 02:30-04:15 ReSch
6                           NaN                          OS (AI-J)
7                           NaN                        Islamic (A)
8                           NaN                                NaN
9                           NaN                 S/w Re-Engg (SE-R)
10                          NaN                                NaN
11                          NaN                        PPIT (CS-A)
12                          NaN                    Info Sec (CS-B)
13                          NaN                        PPIT (CS-C)
14                          NaN                     OOP (CS-A, 22)
15                          NaN                         DLD (CY-C)
16                          NaN                 Fund of Mgt (SE-A)
17                          NaN                    Mktg Mgt (CS-C)
18                          NaN                 Freelancing (CS-C)
19                          NaN                       OS (CS-A,21)
20                          NaN                        PPIT (DS-N)
21                          NaN                                NaN
22                          NaN                    Diff Eq (D, 22)
23                          NaN                                NaN
24                          NaN                                NaN
25                          NaN                 Comp Vision (AI-J)
26                          NaN                                NaN
27                          NaN                       DB (CS-C,21)
28                          NaN                                NaN
29                          NaN                                NaN
30                          NaN                     OOP (CY-A, 22)
31                          NaN                                NaN
32                          NaN                                NaN
33                          NaN                                NaN
34                          NaN                                NaN
35                          NaN                                FSM
36                          NaN                                NaN
37                          NaN                                NaN

                            14                     16                  19  \
0                          NaN            03:55-05:15        05:20-06:40
1                          NaN                    NaN              Adv OS
2                          NaN  Info Sec (CS-F) ReSch        Adv Comp Net
3                          NaN  Calculus (CS-D) ReSch      Adv Qual Assur
4                          NaN                    NaN       Deep Learning
5                          NaN                    NaN  Stat & Math for DS
6                          NaN                    NaN                 NaN
7                          NaN                    NaN                 NaN
8   Islamic (CS-F) 03:05-04:50                    NaN                 NaN
9                          NaN                    NaN                 NaN
10       LA (CS-A) 03:00-04:20                    NaN                 NaN
11                         NaN        Info Sec (CS-A)                 NaN
12                         NaN            PPIT (CS-B)                 NaN
13                         NaN        Info Sec (CS-C)                 NaN
14                         NaN         OOP (CS-B, 22)                 NaN
15                         NaN                    NaN                 NaN
16                         NaN                    NaN                 NaN
17                         NaN        Mktg Mgt (SE-C)                 NaN
18                         NaN                    NaN                 NaN
19                         NaN           OS (CS-B,21)                 NaN
20                         NaN           DB (CS-D,21)                 NaN
21                         NaN      Deep Learn (DS-N)                 NaN
22                         NaN        Diff Eq (E, 22)                 NaN
23                         NaN                    NaN                 NaN
24                         NaN                    NaN                 NaN
25                         NaN     Comp Vision (AI-K)                 NaN
26                         NaN                    NaN                 NaN
27                         NaN        Pak Studies (A)                 NaN
28                         NaN                    NaN                 NaN
29                         NaN                    NaN                 NaN
30                         NaN                    NaN                 NaN
31                         NaN                    NaN                 NaN
32                         NaN                    NaN                 NaN
33                         NaN                    NaN                 NaN
34                         NaN                    NaN                 NaN
35                         NaN                    FSM                 NaN
36                         NaN                    NaN                 NaN
37                         NaN                    NaN                 NaN

                 22
0       06:45-08:05
1          Adv Algo
2               NaN
3      Adv S/w Arch
4            Adv AI
5   DS Tools & Tech
6               NaN
7               NaN
8               NaN
9               NaN
10              NaN
11              NaN
12              NaN
13              NaN
14              NaN
15              NaN
16              NaN
17              NaN
18              NaN
19              NaN
20              NaN
21              NaN
22              NaN
23              NaN
24              NaN
25              NaN
26              NaN
27              NaN
28              NaN
29              NaN
30              NaN
31              NaN
32              NaN
33              NaN
34              NaN
35              NaN
36              NaN
37              NaN

In [4]:
import pandas as pd

# Load the Excel file
excel_file = "timetable.xlsx"
xl = pd.ExcelFile(excel_file)

# Initialize an empty list to store DataFrames for each sheet
data_frames = []

# Loop through the sheets in the Excel file
for sheet_name in xl.sheet_names:
    # Read each sheet into a DataFrame
    df = xl.parse(sheet_name)
    
    # Add a new column with the sheet name to identify the source of data
    df['Sheet Name'] = sheet_name
    
    # Append the DataFrame to the list
    data_frames.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(data_frames, ignore_index=True)

# Save the combined data to a CSV file
csv_file = "combined_timetable.csv"
combined_df.to_csv(csv_file, index=False)

print(f"Data from all sheets has been combined and saved to {csv_file}.")

Data from all sheets has been combined and saved to combined_timetable.csv.

In [3]:
import pandas as pd

# Load the Excel file into a DataFrame (replace 'file.xlsx' with your file path)



subject = input("Enter the subject: ")


class_names = []
room_numbers = []
class_times = []


for index, row in df.iterrows():

    row_values = [str(cell) for cell in row]


    for col_index in range(1, len(row_values)):
        if subject in row_values[col_index]:
            class_name = row_values[col_index]
            room_number = row_values[0]
            

            class_times_dict = {
                1: "08:30-09:50",
                2: "10:00-11:20",
                3: "11:30-12:50",
                4: "1:00-2:20",
                5: "2:30-3:50",
                6: "3:55-5:15"
            }
            

            class_time = class_times_dict.get(col_index, "Unknown")
            

            class_names.append(class_name)
            room_numbers.append(room_number)
            class_times.append(class_time)


if class_names:

    for i in range(len(class_names)):
        print(f"Class {i+1} - Class info: {class_names[i]}, Room: {room_numbers[i]}, Class Times: {class_times[i]}")
else:
    print(f"No classes found for {subject}.")

Class 1 - Class info: Algo (CS-B,21), Room: C-301, Class Times: Unknown
Class 2 - Class info: Algo (CS-A, 21), Room: C-406, Class Times: Unknown
Class 3 - Class info: Algo (CS-D, 21), Room: C-406, Class Times: Unknown
Class 4 - Class info: Algo (CS-C,21), Room: B-229, Class Times: Unknown

In [1]:
#Question 3
import pandas as pd


course_allocators_df = pd.read_excel("course_instructors.xlsx", skiprows=2)
timetable_df = pd.read_excel("timetable.xlsx", skiprows=4)
course_allocators_df

,S.#,Code,Course,CHs,Section,Course Instructor,Course Coordinator
0,BS Batch 2023,NaN,NaN,NaN,NaN,NaN,NaN
1,1,CS-1002,Programming Fundamentals (CS),3.0,BCS-1A,Dr. Muhammad Arshad Islam,Dr. Muhammad Arshad Islam
2,NaN,NaN,NaN,NaN,BCS-1B,Dr. Muhammad Arshad Islam,NaN
3,NaN,NaN,NaN,NaN,BCS-1C,Mr. Aqib Rehman,NaN
4,NaN,NaN,NaN,NaN,BCS-1D,Mr. Aqib Rehman,NaN
...,...,...,...,...,...,...,...
299,NaN,SE-5032,Empirical Software Engineering,3.0,MS-A,Dr. Atif Jilani,Dr. Atif Jilani
300,NaN,CS-5035,Applied Image Processing,3.0,MS-A,Dr. Sajid Ali Khan (Visiting),Dr. Sajid Ali Khan (Visiting)
301,NaN,CS-5043,Cloud Computing,3.0,MS-A,Mr. Basharat Hussain (visiting),Mr. Basharat Hussain (visiting)
302,NaN,CY-5002,Machine Learning for Cyber Security,3.0,MS-A,Dr. Qaiser Shafi,Dr. Qaiser Shafi
303,289,CS-5113,Ethical Hacking,3.0,MS-A,Mr. Mehmood Ul Hassan,Mr. Mehmood Ul Hassan

In [ ]:
rgb_color = 'FFFFB740'

# for finding those cells which have the same rgb color value
for row in sheet.iter_rows(min_row=1, max_row=40, min_col=1, max_col=sheet.max_column):
    for cell in row:
        print(cell.coordinate)
        if cell.fill.start_color.rgb == rgb_color:
            print(f'Value found in cell {cell.coordinate}, RGB color: {rgb_color}')